# Author: Sakthi Santhosh
# Created on: 05/10/2023
version: 0.0
os: linux
files:
  - source: /
    destination: /app/
hooks:
  BeforeInstall:
    - location: /scripts/before-install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: /scripts/after-install.sh
      timeout: 300
      runas: ec2-user
